<?php
declare(strict_types=1);

namespace App\Controllers\Admin;

use App\Http\Middleware\AuthGuard;
use App\Models\NotificationModel;
use App\Services\MailService;
use App\Support\Lang;
use App\Support\Mailer;
use App\Support\Paginator;
use App\Support\Request;
use App\Support\Response;
use App\Support\View;

/**
 * Admin notification feed. Rows are generated by App\Services\SchedulerService
 * (run daily by scripts/scheduler.php). The feed is global to the admin role
 * (a small construction company shares one operational view).
 */
final class NotificationController
{
    /** GET /admin/notifications — list (all or unread only via ?filter=unread). */
    public function index(Request $request): void
    {
        AuthGuard::require($request, ['admin']);

        $model      = new NotificationModel();
        $unreadOnly = (string) $request->input('filter', '') === 'unread';
        $paginator  = Paginator::fromRequest($request, $model->countAll($unreadOnly), 30);

        Response::html(View::render('admin/notifications/index', [
            'title'         => Lang::get('notifications.title'),
            'notifications' => $model->all($unreadOnly, null, $paginator->perPage, $paginator->offset),
            'unreadOnly'    => $unreadOnly,
            'unreadCount'   => $model->unreadCount(),
            'paginator'     => $paginator,
        ], 'layout'));
    }

    /** POST /admin/notifications/{id}/read — mark one as read. */
    public function read(Request $request, string $id): void
    {
        AuthGuard::require($request, ['admin']);
        (new NotificationModel())->markRead((int) $id);
        Response::ok();
    }

    /** POST /admin/notifications/read-all — mark every unread notification read. */
    public function readAll(Request $request): void
    {
        AuthGuard::require($request, ['admin']);
        Response::ok(['count' => (new NotificationModel())->markAllRead()]);
    }

    /**
     * POST /admin/notifications/test-email — send a test message to the logged-in
     * admin so the SMTP configuration can be verified from the UI. Reports whether
     * mail is enabled, sent, or failed.
     */
    public function testEmail(Request $request): void
    {
        $user = AuthGuard::require($request, ['admin']);

        if (!Mailer::isEnabled()) {
            Response::fail(Lang::get('mail.test_disabled'), 422);
            return;
        }
        $to = (string) ($user['email'] ?? '');
        if (MailService::test($to)) {
            Response::ok(['message' => sprintf(Lang::get('mail.test_sent'), $to)]);
            return;
        }
        Response::fail(Lang::get('mail.test_failed'), 502);
    }
}
