<?php
declare(strict_types=1);

namespace App\Controllers\Admin;

use App\Http\Middleware\AuthGuard;
use App\Models\NotificationModel;
use App\Support\Lang;
use App\Support\Request;
use App\Support\Response;
use App\Support\View;

/**
 * Admin notification feed. Rows are generated by App\Services\SchedulerService
 * (run daily by scripts/scheduler.php). The feed is global to the admin role
 * (a small construction company shares one operational view).
 */
final class NotificationController
{
    /** GET /admin/notifications — list (all or unread only via ?filter=unread). */
    public function index(Request $request): void
    {
        AuthGuard::require($request, ['admin']);

        $model      = new NotificationModel();
        $unreadOnly = (string) $request->input('filter', '') === 'unread';

        Response::html(View::render('admin/notifications/index', [
            'title'         => Lang::get('notifications.title'),
            'notifications' => $model->all($unreadOnly),
            'unreadOnly'    => $unreadOnly,
            'unreadCount'   => $model->unreadCount(),
        ], 'layout'));
    }

    /** POST /admin/notifications/{id}/read — mark one as read. */
    public function read(Request $request, string $id): void
    {
        AuthGuard::require($request, ['admin']);
        (new NotificationModel())->markRead((int) $id);
        Response::ok();
    }

    /** POST /admin/notifications/read-all — mark every unread notification read. */
    public function readAll(Request $request): void
    {
        AuthGuard::require($request, ['admin']);
        Response::ok(['count' => (new NotificationModel())->markAllRead()]);
    }
}
