-- In-app notification feed (admin-facing). Generated by scripts/scheduler.php:
-- compliance-document expiries, auto-expired quotes, overdue interventions, low stock.
-- dedup_key makes generation idempotent (INSERT IGNORE): one row per logical event,
-- so a daily scheduler run never duplicates an existing alert.
-- Statements are separated by a semicolon followed by a newline (see database/migrate.php).

CREATE TABLE notifications (
    id          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    type        ENUM('compliance_expiry','quote_expired','intervention_overdue','low_stock','system') NOT NULL,
    severity    ENUM('info','warning','danger') NOT NULL DEFAULT 'info',
    title       VARCHAR(190) NOT NULL,
    body        VARCHAR(500) NULL,
    link        VARCHAR(255) NULL,
    dedup_key   VARCHAR(190) NULL,
    is_read     TINYINT(1) NOT NULL DEFAULT 0,
    created_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    read_at     DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_notifications_dedup (dedup_key),
    KEY idx_notifications_unread (is_read, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
