<?php
declare(strict_types=1);

namespace App\Models;

use App\Support\Database;

/**
 * In-app notification feed. Two audiences share one table, separated by user_id:
 *   - user_id IS NULL  → the admin/global feed. Rows are generated by
 *                        App\Services\SchedulerService (daily cron) and this is the
 *                        historical behaviour — every admin-facing query passes no
 *                        $userId and therefore reads only these rows.
 *   - user_id = N      → a single user's feed (e.g. a client portal user notified
 *                        that a quote was sent). Written via App\Services\NotificationService.
 *
 * createIfAbsent() is idempotent on dedup_key (INSERT IGNORE), so re-running a
 * generator never duplicates an existing alert.
 */
final class NotificationModel
{
    /**
     * Insert a notification unless one with the same dedup_key already exists.
     * Returns true when a new row was created, false when it was a duplicate.
     * A null dedup_key is never de-duplicated (always inserted). Pass user_id to
     * target one user; omit it (null) for the admin/global feed.
     *
     * @param array{type:string,severity?:string,title:string,body?:?string,link?:?string,dedup_key?:?string,user_id?:?int} $data
     */
    public function createIfAbsent(array $data): bool
    {
        $stmt = Database::pdo()->prepare(
            'INSERT IGNORE INTO notifications (user_id, type, severity, title, body, link, dedup_key)
             VALUES (:user_id, :type, :severity, :title, :body, :link, :dedup_key)'
        );
        $stmt->execute([
            ':user_id'   => $data['user_id'] ?? null,
            ':type'      => $data['type'],
            ':severity'  => $data['severity'] ?? 'info',
            ':title'     => $data['title'],
            ':body'      => $data['body'] ?? null,
            ':link'      => $data['link'] ?? null,
            ':dedup_key' => $data['dedup_key'] ?? null,
        ]);
        return $stmt->rowCount() > 0;
    }

    public function unreadCount(?int $userId = null): int
    {
        [$scope, $bind] = $this->scope($userId);
        $stmt = Database::pdo()->prepare("SELECT COUNT(*) FROM notifications WHERE is_read = 0 AND {$scope}");
        $stmt->execute($bind);
        return (int) $stmt->fetchColumn();
    }

    /** @return array<int,array<string,mixed>> */
    public function recent(int $limit = 8, ?int $userId = null): array
    {
        $limit          = max(1, min(50, $limit));
        [$scope, $bind] = $this->scope($userId);
        $stmt = Database::pdo()->prepare(
            "SELECT * FROM notifications WHERE {$scope}
             ORDER BY is_read ASC, created_at DESC, id DESC LIMIT {$limit}"
        );
        $stmt->execute($bind);
        return $stmt->fetchAll();
    }

    /** @return array<int,array<string,mixed>> */
    public function all(bool $unreadOnly = false, ?int $userId = null): array
    {
        [$scope, $bind] = $this->scope($userId);
        $sql = "SELECT * FROM notifications WHERE {$scope}";
        if ($unreadOnly) {
            $sql .= ' AND is_read = 0';
        }
        $sql .= ' ORDER BY is_read ASC, created_at DESC, id DESC LIMIT 500';
        $stmt = Database::pdo()->prepare($sql);
        $stmt->execute($bind);
        return $stmt->fetchAll();
    }

    public function markRead(int $id, ?int $userId = null): bool
    {
        [$scope, $bind] = $this->scope($userId);
        $stmt = Database::pdo()->prepare(
            "UPDATE notifications SET is_read = 1, read_at = NOW() WHERE id = ? AND is_read = 0 AND {$scope}"
        );
        $stmt->execute(array_merge([$id], $bind));
        return $stmt->rowCount() > 0;
    }

    public function markAllRead(?int $userId = null): int
    {
        [$scope, $bind] = $this->scope($userId);
        $stmt = Database::pdo()->prepare(
            "UPDATE notifications SET is_read = 1, read_at = NOW() WHERE is_read = 0 AND {$scope}"
        );
        $stmt->execute($bind);
        return $stmt->rowCount();
    }

    /**
     * Audience filter: null → the admin/global feed (user_id IS NULL); an int → that
     * user's own rows. Returns the SQL fragment and its positional bind values.
     *
     * @return array{0:string,1:array<int,int>}
     */
    private function scope(?int $userId): array
    {
        return $userId === null
            ? ['user_id IS NULL', []]
            : ['user_id = ?', [$userId]];
    }
}
